In [4]:
!pip install pandas
!pip install langchain_community
!pip install langchain-tavily
!pip install seaborn
!piip install python-dotenv
!pip install openai
!pip install chromadb

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: langchain_community in /opt/anaconda3/lib/python3.13/site-packages (0.4.1)
Requirement already satisfied: langchain-core<2.0.0,>=1.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from langchain_community) (1.2.26)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from langchain_community) (1.0.3)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in /opt/anaconda3/lib/python3.13/site-packages (from langchain_community) (2.0.43)
Requirement already satisfied: requests<3.0.0,>=2.32.5 in /opt/anaconda3/lib/python3.13/site-packages (from langchain_community) (2.32.5)
Requirement already satisfied: PyYAML<7.0.0,>=5.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from langchain_community) (6.0.3)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /opt/anaconda3/lib/python3.13/site-packages (from langchain_community) (3.13.2)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from langchain_community) (9.1.2)
Requirement already satisfied: dataclasses-json<0.7.0,>=0.6.7 in /opt/anaconda3/lib/python3.13/site-packages (from langchain_community) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /opt/anaconda3/lib/python3.13/site-packages (from langchain_community) (2.12.0)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /opt/anaconda3/lib/python3.13/site-packages (from langchain_community) (0.7.25)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /opt/anaconda3/lib/python3.13/site-packages (from langchain_community) (0.4.3)
Requirement already satisfied: numpy>=2.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from langchain_community) (2.3.5)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.22.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /opt/anaconda3/lib/python3.13/site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain_community) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /opt/anaconda3/lib/python3.13/site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain_community) (0.9.0)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.1 in /opt/anaconda3/lib/python3.13/site-packages (from langchain-classic<2.0.0,>=1.0.0->langchain_community) (1.1.1)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /opt/anaconda3/lib/python3.13/site-packages (from langchain-classic<2.0.0,>=1.0.0->langchain_community) (2.12.4)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /opt/anaconda3/lib/python3.13/site-packages (from langchain-core<2.0.0,>=1.0.1->langchain_community) (1.33)
Requirement already satisfied: packaging>=23.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from langchain-core<2.0.0,>=1.0.1->langchain_community) (25.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /opt/anaconda3/lib/python3.13/site-packages (from langchain-core<2.0.0,>=1.0.1->langchain_community) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /opt/anaconda3/lib/python3.13/site-packages (from langchain-core<2.0.0,>=1.0.1->langchain_community) (0.14.1)
Requirement already satisfied: jsonpointer>=1.9 in /opt/anaconda3/lib/python3.13/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.0.1->langchain_community) (3.0.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /opt/anaconda3/lib/python3.13/site-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /opt/anaconda3/lib/python3.13/site-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (3.11.8)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (1.0.0)
Requirement already satisfied: xxhash>=3.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /opt/anaconda3/lib/python3.13/site-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (0.24.0)
Requirement already satisfied: anyio in /opt/anaconda3/lib/python3.13/site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain_community) (4.10.0)
Requirement already satisfied: certifi in /opt/anaconda3/lib/python3.13/site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain_community) (2025.11.12)
Requirement already satisfied: httpcore==1.* in /opt/anaconda3/lib/python3.13/site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain_community) (1.0.9)
Requirement already satisfied: idna in /opt/anaconda3/lib/python3.13/site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain_community) (3.11)
Requirement already satisfied: h11>=0.16 in /opt/anaconda3/lib/python3.13/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain_community) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.0->langchain_community) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.0->langchain_community) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.0->langchain_community) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain_community) (1.1.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.32.5->langchain_community) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.32.5->langchain_community) (2.5.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain_community) (1.0.0)
Requirement already satisfied: sniffio>=1.1 in /opt/anaconda3/lib/python3.13/site-packages (from anyio->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain_community) (1.3.0)
Requirement already satisfied: langchain-tavily in /opt/anaconda3/lib/python3.13/site-packages (0.2.17)
Requirement already satisfied: aiohttp<4.0.0,>=3.11.14 in /opt/anaconda3/lib/python3.13/site-packages (from langchain-tavily) (3.13.2)
Requirement already satisfied: langchain<2.0.0,>=0.3.20 in /opt/anaconda3/lib/python3.13/site-packages (from langchain-tavily) (1.2.15)
Requirement already satisfied: langchain-core<2.0.0,>=0.3.15 in /opt/anaconda3/lib/python3.13/site-packages (from langchain-tavily) (1.2.26)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in /opt/anaconda3/lib/python3.13/site-packages (from langchain-tavily) (2.32.5)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.11.14->langchain-tavily) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.11.14->langchain-tavily) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.11.14->langchain-tavily) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.11.14->langchain-tavily) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.11.14->langchain-tavily) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.11.14->langchain-tavily) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.11.14->langchain-tavily) (1.22.0)
Requirement already satisfied: langgraph<1.2.0,>=1.1.5 in /opt/anaconda3/lib/python3.13/site-packages (from langchain<2.0.0,>=0.3.20->langchain-tavily) (1.1.6)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /opt/anaconda3/lib/python3.13/site-packages (from langchain<2.0.0,>=0.3.20->langchain-tavily) (2.12.4)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /opt/anaconda3/lib/python3.13/site-packages (from langchain-core<2.0.0,>=0.3.15->langchain-tavily) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /opt/anaconda3/lib/python3.13/site-packages (from langchain-core<2.0.0,>=0.3.15->langchain-tavily) (0.7.25)
Requirement already satisfied: packaging>=23.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from langchain-core<2.0.0,>=0.3.15->langchain-tavily) (25.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from langchain-core<2.0.0,>=0.3.15->langchain-tavily) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from langchain-core<2.0.0,>=0.3.15->langchain-tavily) (9.1.2)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /opt/anaconda3/lib/python3.13/site-packages (from langchain-core<2.0.0,>=0.3.15->langchain-tavily) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /opt/anaconda3/lib/python3.13/site-packages (from langchain-core<2.0.0,>=0.3.15->langchain-tavily) (0.14.1)
Requirement already satisfied: jsonpointer>=1.9 in /opt/anaconda3/lib/python3.13/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=0.3.15->langchain-tavily) (3.0.0)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=2.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from langgraph<1.2.0,>=1.1.5->langchain<2.0.0,>=0.3.20->langchain-tavily) (4.0.1)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.9 in /opt/anaconda3/lib/python3.13/site-packages (from langgraph<1.2.0,>=1.1.5->langchain<2.0.0,>=0.3.20->langchain-tavily) (1.0.9)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from langgraph<1.2.0,>=1.1.5->langchain<2.0.0,>=0.3.20->langchain-tavily) (0.3.12)
Requirement already satisfied: xxhash>=3.5.0 in /opt/anaconda3/lib/python3.13/site-packages (from langgraph<1.2.0,>=1.1.5->langchain<2.0.0,>=0.3.20->langchain-tavily) (3.6.0)
Requirement already satisfied: ormsgpack>=1.12.0 in /opt/anaconda3/lib/python3.13/site-packages (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph<1.2.0,>=1.1.5->langchain<2.0.0,>=0.3.20->langchain-tavily) (1.12.2)
Requirement already satisfied: httpx>=0.25.2 in /opt/anaconda3/lib/python3.13/site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain<2.0.0,>=0.3.20->langchain-tavily) (0.28.1)
Requirement already satisfied: orjson>=3.11.5 in /opt/anaconda3/lib/python3.13/site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain<2.0.0,>=0.3.20->langchain-tavily) (3.11.8)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=0.3.15->langchain-tavily) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /opt/anaconda3/lib/python3.13/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=0.3.15->langchain-tavily) (0.24.0)
Requirement already satisfied: anyio in /opt/anaconda3/lib/python3.13/site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain<2.0.0,>=0.3.20->langchain-tavily) (4.10.0)
Requirement already satisfied: certifi in /opt/anaconda3/lib/python3.13/site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain<2.0.0,>=0.3.20->langchain-tavily) (2025.11.12)
Requirement already satisfied: httpcore==1.* in /opt/anaconda3/lib/python3.13/site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain<2.0.0,>=0.3.20->langchain-tavily) (1.0.9)
Requirement already satisfied: idna in /opt/anaconda3/lib/python3.13/site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain<2.0.0,>=0.3.20->langchain-tavily) (3.11)
Requirement already satisfied: h11>=0.16 in /opt/anaconda3/lib/python3.13/site-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain<2.0.0,>=0.3.20->langchain-tavily) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.7.4->langchain<2.0.0,>=0.3.20->langchain-tavily) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.7.4->langchain<2.0.0,>=0.3.20->langchain-tavily) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.7.4->langchain<2.0.0,>=0.3.20->langchain-tavily) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.32.3->langchain-tavily) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.32.3->langchain-tavily) (2.5.0)
Requirement already satisfied: sniffio>=1.1 in /opt/anaconda3/lib/python3.13/site-packages (from anyio->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain<2.0.0,>=0.3.20->langchain-tavily) (1.3.0)
Requirement already satisfied: seaborn in /opt/anaconda3/lib/python3.13/site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /opt/anaconda3/lib/python3.13/site-packages (from seaborn) (2.3.5)
Requirement already satisfied: pandas>=1.2 in /opt/anaconda3/lib/python3.13/site-packages (from seaborn) (2.3.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /opt/anaconda3/lib/python3.13/site-packages (from seaborn) (3.10.6)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
zsh:1: command not found: piip
Requirement already satisfied: openai in /opt/anaconda3/lib/python3.13/site-packages (2.30.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /opt/anaconda3/lib/python3.13/site-packages (from openai) (4.10.0)
Requirement already satisfied: distro<2,>=1.7.0 in /opt/anaconda3/lib/python3.13/site-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /opt/anaconda3/lib/python3.13/site-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /opt/anaconda3/lib/python3.13/site-packages (from openai) (0.13.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /opt/anaconda3/lib/python3.13/site-packages (from openai) (2.12.4)
Requirement already satisfied: sniffio in /opt/anaconda3/lib/python3.13/site-packages (from openai) (1.3.0)
Requirement already satisfied: tqdm>4 in /opt/anaconda3/lib/python3.13/site-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /opt/anaconda3/lib/python3.13/site-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in /opt/anaconda3/lib/python3.13/site-packages (from anyio<5,>=3.5.0->openai) (3.11)
Requirement already satisfied: certifi in /opt/anaconda3/lib/python3.13/site-packages (from httpx<1,>=0.23.0->openai) (2025.11.12)
Requirement already satisfied: httpcore==1.* in /opt/anaconda3/lib/python3.13/site-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /opt/anaconda3/lib/python3.13/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic<3,>=1.9.0->openai) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic<3,>=1.9.0->openai) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)
Requirement already satisfied: chromadb in /opt/anaconda3/lib/python3.13/site-packages (1.5.5)
Requirement already satisfied: build>=1.0.3 in /opt/anaconda3/lib/python3.13/site-packages (from chromadb) (1.4.2)
Requirement already satisfied: pydantic>=2.0 in /opt/anaconda3/lib/python3.13/site-packages (from chromadb) (2.12.4)

In [5]:
!pip install openai

Requirement already satisfied: openai in /opt/anaconda3/lib/python3.13/site-packages (2.30.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /opt/anaconda3/lib/python3.13/site-packages (from openai) (4.10.0)
Requirement already satisfied: distro<2,>=1.7.0 in /opt/anaconda3/lib/python3.13/site-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /opt/anaconda3/lib/python3.13/site-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /opt/anaconda3/lib/python3.13/site-packages (from openai) (0.13.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /opt/anaconda3/lib/python3.13/site-packages (from openai) (2.12.4)
Requirement already satisfied: sniffio in /opt/anaconda3/lib/python3.13/site-packages (from openai) (1.3.0)
Requirement already satisfied: tqdm>4 in /opt/anaconda3/lib/python3.13/site-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /opt/anaconda3/lib/python3.13/site-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in /opt/anaconda3/lib/python3.13/site-packages (from anyio<5,>=3.5.0->openai) (3.11)
Requirement already satisfied: certifi in /opt/anaconda3/lib/python3.13/site-packages (from httpx<1,>=0.23.0->openai) (2025.11.12)
Requirement already satisfied: httpcore==1.* in /opt/anaconda3/lib/python3.13/site-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /opt/anaconda3/lib/python3.13/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic<3,>=1.9.0->openai) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic<3,>=1.9.0->openai) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)

In [6]:
import openai
print("OpenAI installed successfully")

OpenAI installed successfully

In [7]:
import sys
print(sys.executable)

/opt/anaconda3/envs/tf-env/bin/python

In [8]:
import sys
!{sys.executable} -m pip install python-dotenv

Requirement already satisfied: python-dotenv in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (1.2.2)

In [9]:
import sys
!{sys.executable} -m pip install chromadb

Requirement already satisfied: chromadb in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (1.5.5)
Requirement already satisfied: build>=1.0.3 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from chromadb) (1.4.2)
Requirement already satisfied: pydantic>=2.0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from chromadb) (2.12.5)
Requirement already satisfied: pydantic-settings>=2.0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from chromadb) (2.13.1)
Requirement already satisfied: pybase64>=1.4.1 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from chromadb) (1.4.3)
Requirement already satisfied: uvicorn>=0.18.3 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.43.0)
Requirement already satisfied: numpy>=1.22.5 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from chromadb) (1.26.4)
Requirement already satisfied: typing-extensions>=4.5.0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from chromadb) (4.15.0)
Requirement already satisfied: onnxruntime>=1.14.1 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from chromadb) (1.23.2)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from chromadb) (1.40.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from chromadb) (1.40.0)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from chromadb) (1.40.0)
Requirement already satisfied: tokenizers>=0.13.2 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from chromadb) (0.22.2)
Requirement already satisfied: pypika>=0.48.9 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from chromadb) (0.51.1)
Requirement already satisfied: tqdm>=4.65.0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from chromadb) (4.67.3)
Requirement already satisfied: overrides>=7.3.1 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from chromadb) (7.7.0)
Requirement already satisfied: importlib-resources in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from chromadb) (6.5.2)
Requirement already satisfied: grpcio>=1.58.0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from chromadb) (1.80.0)
Requirement already satisfied: bcrypt>=4.0.1 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from chromadb) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from chromadb) (0.24.1)
Requirement already satisfied: kubernetes>=28.1.0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from chromadb) (35.0.0)
Requirement already satisfied: tenacity>=8.2.3 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from chromadb) (9.1.4)
Requirement already satisfied: pyyaml>=6.0.0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from chromadb) (6.0.3)
Requirement already satisfied: mmh3>=4.0.1 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from chromadb) (5.2.1)
Requirement already satisfied: orjson>=3.9.12 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from chromadb) (3.11.8)
Requirement already satisfied: httpx>=0.27.0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from chromadb) (14.3.3)
Requirement already satisfied: jsonschema>=4.19.0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from chromadb) (4.26.0)
Requirement already satisfied: packaging>=24.0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from build>=1.0.3->chromadb) (26.0)
Requirement already satisfied: pyproject_hooks in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from build>=1.0.3->chromadb) (1.2.0)
Requirement already satisfied: tomli>=1.1.0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from build>=1.0.3->chromadb) (2.4.1)
Requirement already satisfied: anyio in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from httpx>=0.27.0->chromadb) (4.13.0)
Requirement already satisfied: certifi in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from httpx>=0.27.0->chromadb) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: idna in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from httpx>=0.27.0->chromadb) (3.11)
Requirement already satisfied: h11>=0.16 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Requirement already satisfied: attrs>=22.2.0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from jsonschema>=4.19.0->chromadb) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from jsonschema>=4.19.0->chromadb) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from jsonschema>=4.19.0->chromadb) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from jsonschema>=4.19.0->chromadb) (0.30.0)
Requirement already satisfied: six>=1.9.0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from kubernetes>=28.1.0->chromadb) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from kubernetes>=28.1.0->chromadb) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from kubernetes>=28.1.0->chromadb) (1.9.0)
Requirement already satisfied: requests in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from kubernetes>=28.1.0->chromadb) (2.33.1)
Requirement already satisfied: requests-oauthlib in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: urllib3!=2.6.0,>=1.24.2 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from kubernetes>=28.1.0->chromadb) (2.6.3)
Requirement already satisfied: durationpy>=0.7 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from kubernetes>=28.1.0->chromadb) (0.10)
Requirement already satisfied: coloredlogs in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from onnxruntime>=1.14.1->chromadb) (15.0.1)
Requirement already satisfied: flatbuffers in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from onnxruntime>=1.14.1->chromadb) (25.12.19)
Requirement already satisfied: protobuf in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from onnxruntime>=1.14.1->chromadb) (6.33.6)
Requirement already satisfied: sympy in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from onnxruntime>=1.14.1->chromadb) (1.14.0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from opentelemetry-api>=1.2.0->chromadb) (8.7.1)
Requirement already satisfied: zipp>=3.20 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.2.0->chromadb) (3.23.0)
Requirement already satisfied: googleapis-common-protos~=1.57 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.74.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.40.0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.40.0)
Requirement already satisfied: opentelemetry-proto==1.40.0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.40.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.61b0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from opentelemetry-sdk>=1.2.0->chromadb) (0.61b0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from pydantic>=2.0->chromadb) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from pydantic>=2.0->chromadb) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from pydantic>=2.0->chromadb) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from pydantic-settings>=2.0->chromadb) (1.2.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from rich>=10.11.0->chromadb) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from rich>=10.11.0->chromadb) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb) (0.1.2)
Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from tokenizers>=0.13.2->chromadb) (1.9.0)
Requirement already satisfied: filelock>=3.10.0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (2026.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (1.4.3)
Requirement already satisfied: click>=8.2.1 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from typer>=0.9.0->chromadb) (8.3.2)
Requirement already satisfied: shellingham>=1.3.0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from typer>=0.9.0->chromadb) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from typer>=0.9.0->chromadb) (0.0.4)
Requirement already satisfied: httptools>=0.6.3 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.7.1)
Requirement already satisfied: uvloop>=0.15.1 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.22.1)
Requirement already satisfied: watchfiles>=0.20 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.1.1)
Requirement already satisfied: websockets>=10.4 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from uvicorn[standard]>=0.18.3->chromadb) (16.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from anyio->httpx>=0.27.0->chromadb) (1.3.1)
Requirement already satisfied: humanfriendly>=9.1 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from coloredlogs->onnxruntime>=1.14.1->chromadb) (10.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from requests->kubernetes>=28.1.0->chromadb) (3.4.7)
Requirement already satisfied: oauthlib>=3.0.0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from requests-oauthlib->kubernetes>=28.1.0->chromadb) (3.3.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/anaconda3/envs/tf-env/lib/python3.10/site-packages (from sympy->onnxruntime>=1.14.1->chromadb) (1.3.0)

In [10]:
import pandas as pd
import numpy as np
import json
import re
from typing import List, Dict, Any, Tuple
from sentence_transformers import SentenceTransformer
from openai import OpenAI
import time
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import seaborn as sns
from dotenv import load_dotenv
import openai
import os

/opt/anaconda3/envs/tf-env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [11]:
load_dotenv()

openai_api_key = os.getenv("OPEN_AI_KEY")
tavily_api_key = os.getenv("TAVILY_API_KEY")

In [12]:
df_qa = pd.read_csv("train.csv")
df_qa = df_qa.sample(500, random_state=0).reset_index(drop=True)

In [13]:
df_qa.head()

,qtype,Question,Answer
0,frequency,How many people are affected by X-linked chond...,The prevalence of X-linked chondrodysplasia pu...
1,treatment,What are the treatments for Kawasaki disease ?,These resources address the diagnosis or manag...
2,genetic changes,What are the genetic changes related to Ellis-...,Ellis-van Creveld syndrome can be caused by mu...
3,symptoms,What are the symptoms of Renal dysplasia-limb ...,What are the signs and symptoms of Renal dyspl...
4,information,What is (are) Fraser syndrome ?,Fraser syndrome is a rare disorder that affect...

In [14]:
df_qa['combined_text'] = (
    "Question: " + df_qa['Question'].astype(str) + '. ' +
    "Answer: " + df_qa['Answer'].astype(str) + '. '+
    "Type: " +df_qa['qtype'].astype(str)+'. '
)
df_qa.head()

,qtype,Question,Answer,combined_text
0,frequency,How many people are affected by X-linked chond...,The prevalence of X-linked chondrodysplasia pu...,Question: How many people are affected by X-li...
1,treatment,What are the treatments for Kawasaki disease ?,These resources address the diagnosis or manag...,Question: What are the treatments for Kawasaki...
2,genetic changes,What are the genetic changes related to Ellis-...,Ellis-van Creveld syndrome can be caused by mu...,Question: What are the genetic changes related...
3,symptoms,What are the symptoms of Renal dysplasia-limb ...,What are the signs and symptoms of Renal dyspl...,Question: What are the symptoms of Renal dyspl...
4,information,What is (are) Fraser syndrome ?,Fraser syndrome is a rare disorder that affect...,Question: What is (are) Fraser syndrome ?. Ans...

In [15]:
df_md = pd.read_csv('medical_device_manuals_dataset.csv')
df_md = df_md.sample(500, random_state=0).reset_index(drop=True)
df_md.head()

,Device_Name,Model_Number,Manufacturer,Manual_Version,Publication_Date,Device_Class,Regulatory_Approval_ID,Patient_Population,Indications_for_Use,Contraindications,Sterilization_Method,Number_of_Warnings,Number_of_Cautions,Device_Lifetime_Years,Device_Weight_kg,Max_Operating_Temperature_C
0,Electrosurgical Unit,Model 1606,Zimmer Biomet,2023-04-Z,2018-04-28,Class IIb,MDR-847127,All,Used for thermal therapy guidance in oncology ...,Contraindicated in presence of radio frequenci...,Hydrogen Peroxide Plasma,10,15,15.0,6.71,27.0
1,Dialysis Machine,X-6538,3M Healthcare,v2.8,2018-04-03,Class I,MDR-416480,Adult (>65),Used for post-operative chemotherapy managemen...,NaN,Gamma Irradiation,8,11,11.0,NaN,17.0
2,Ventilator,SON230,Sonova,Version 13,2022-02-24,Class III,BLA670706,Adult (>65),Indicated for real-time temperature assessment...,Do not use during general anesthesia administr...,Pre-Sterilized,18,28,11.0,149.42,25.0
3,Dialysis Machine,Max787,Boston Scientific,v4.7,2016-05-08,Class II,BLA131698,Neonatal,Intended for sterilization guidance during min...,"Not recommended during pregnancy, lactation, o...",NaN,10,15,15.0,20.96,20.0
4,Electrosurgical Unit,Plus691,Abbott,2020-03-Q,2015-01-30,Class III,H127393,Pediatric,Intended for life support evaluation in rehabi...,Contraindicated in patients with severe diabet...,Single-Use Sterile,13,17,8.0,7.75,31.0

In [16]:
df_md['combined_text'] = (
    "Device Name: " + df_md['Device_Name'].astype(str) + ". " +
    "Model: " + df_md['Model_Number'].astype(str) + ". " +
    "Manufacturer: " + df_md['Manufacturer'].astype(str) + ". " +
    "Indications: " + df_md['Indications_for_Use'].astype(str) + ". " +
    "Contraindications: " + df_md['Contraindications'].fillna('None').astype(str)
)
df_md.head()

,Device_Name,Model_Number,Manufacturer,Manual_Version,Publication_Date,Device_Class,Regulatory_Approval_ID,Patient_Population,Indications_for_Use,Contraindications,Sterilization_Method,Number_of_Warnings,Number_of_Cautions,Device_Lifetime_Years,Device_Weight_kg,Max_Operating_Temperature_C,combined_text
0,Electrosurgical Unit,Model 1606,Zimmer Biomet,2023-04-Z,2018-04-28,Class IIb,MDR-847127,All,Used for thermal therapy guidance in oncology ...,Contraindicated in presence of radio frequenci...,Hydrogen Peroxide Plasma,10,15,15.0,6.71,27.0,Device Name: Electrosurgical Unit. Model: Mode...
1,Dialysis Machine,X-6538,3M Healthcare,v2.8,2018-04-03,Class I,MDR-416480,Adult (>65),Used for post-operative chemotherapy managemen...,NaN,Gamma Irradiation,8,11,11.0,NaN,17.0,Device Name: Dialysis Machine. Model: X-6538. ...
2,Ventilator,SON230,Sonova,Version 13,2022-02-24,Class III,BLA670706,Adult (>65),Indicated for real-time temperature assessment...,Do not use during general anesthesia administr...,Pre-Sterilized,18,28,11.0,149.42,25.0,Device Name: Ventilator. Model: SON230. Manufa...
3,Dialysis Machine,Max787,Boston Scientific,v4.7,2016-05-08,Class II,BLA131698,Neonatal,Intended for sterilization guidance during min...,"Not recommended during pregnancy, lactation, o...",NaN,10,15,15.0,20.96,20.0,Device Name: Dialysis Machine. Model: Max787. ...
4,Electrosurgical Unit,Plus691,Abbott,2020-03-Q,2015-01-30,Class III,H127393,Pediatric,Intended for life support evaluation in rehabi...,Contraindicated in patients with severe diabet...,Single-Use Sterile,13,17,8.0,7.75,31.0,Device Name: Electrosurgical Unit. Model: Plus...

In [17]:
import chromadb
client = chromadb.PersistentClient(path= './chroma_db')

In [18]:
collection1 = client.get_or_create_collection(name='medical_qna')

In [19]:
df_qa = df_qa.fillna("")

# Convert everything to string (safe fix)
df_qa = df_qa.astype(str)

In [20]:
collection1.add(
    documents=df_qa['combined_text'].tolist(),
    metadatas = df_qa.to_dict(orient='records'),
    ids=df_qa.index.astype(str).tolist()
)

In [21]:
collection2 = client.get_or_create_collection(name='medical_device_manual')

In [22]:
df_md = df_md.fillna("")

# Convert everything to string (safe fix)
df_md = df_md.astype(str)

In [23]:
collection2.add(
    documents=df_md['combined_text'].tolist(),
    metadatas=df_md.to_dict(orient="records"),
    ids=df_md.index.astype(str).tolist(),
)

In [24]:
query = "what are the devices relevant to surgery"
results = collection2.query(query_texts=[query], n_results=3)
print(results)

{'ids': [['403', '142', '82']], 'embeddings': None, 'documents': [['Device Name: Orthopedic Implant. Model: Model 4592. Manufacturer: Intuitive Surgical. Indications: Used for post-operative thermal therapy management in hospital recovery units.. Contraindications: Avoid use if patient has coagulopathy or is receiving iodine compounds.', 'Device Name: Surgical Robot. Model: BIO146. Manufacturer: BioMérieux. Indications: Used for therapeutic drug delivery in neonatal patients requiring wound debridement.. Contraindications: Avoid use in patients with mesh implants or mesh implants. Not suitable for infectious disease isolation.', 'Device Name: Anesthesia Machine. Model: C-1766. Manufacturer: Edwards Lifesciences. Indications: Used for intraoperative sterilization monitoring during complex oncological surgeries.. Contraindications: Avoid use in patients with active hepatic dysfunction or compromised respiratory function.']], 'uris': None, 'included': ['metadatas', 'documents', 'distances'], 'data': None, 'metadatas': [[{'Max_Operating_Temperature_C': 37.0, 'Contraindications': 'Avoid use if patient has coagulopathy or is receiving iodine compounds.', 'Sterilization_Method': 'Dry Heat', 'Indications_for_Use': 'Used for post-operative thermal therapy management in hospital recovery units.', 'Device_Name': 'Orthopedic Implant', 'Number_of_Warnings': 8, 'Number_of_Cautions': 12, 'Manufacturer': 'Intuitive Surgical', 'Publication_Date': '2023-04-14', 'Patient_Population': 'Adult and Pediatric', 'Regulatory_Approval_ID': 'P348923', 'Device_Weight_kg': 0.18, 'combined_text': 'Device Name: Orthopedic Implant. Model: Model 4592. Manufacturer: Intuitive Surgical. Indications: Used for post-operative thermal therapy management in hospital recovery units.. Contraindications: Avoid use if patient has coagulopathy or is receiving iodine compounds.', 'Device_Class': 'Class I', 'Device_Lifetime_Years': 8.0, 'Manual_Version': 'v15.8', 'Model_Number': 'Model 4592'}, {'Patient_Population': 'Infant (0-2)', 'Number_of_Cautions': 28, 'Manual_Version': 'v6.7', 'Manufacturer': 'BioMérieux', 'Max_Operating_Temperature_C': 38.0, 'Device_Lifetime_Years': 11.0, 'Number_of_Warnings': 22, 'Regulatory_Approval_ID': 'BLA631713', 'Device_Name': 'Surgical Robot', 'Model_Number': 'BIO146', 'Device_Class': 'Class III', 'Publication_Date': '2015-05-02', 'combined_text': 'Device Name: Surgical Robot. Model: BIO146. Manufacturer: BioMérieux. Indications: Used for therapeutic drug delivery in neonatal patients requiring wound debridement.. Contraindications: Avoid use in patients with mesh implants or mesh implants. Not suitable for infectious disease isolation.', 'Indications_for_Use': 'Used for therapeutic drug delivery in neonatal patients requiring wound debridement.', 'Contraindications': 'Avoid use in patients with mesh implants or mesh implants. Not suitable for infectious disease isolation.'}, {'Device_Name': 'Anesthesia Machine', 'Manual_Version': 'Rev. 3.2', 'Indications_for_Use': 'Used for intraoperative sterilization monitoring during complex oncological surgeries.', 'Number_of_Warnings': 9, 'Contraindications': 'Avoid use in patients with active hepatic dysfunction or compromised respiratory function.', 'Regulatory_Approval_ID': 'IVDR-159944', 'Sterilization_Method': 'Steam Sterilization', 'Patient_Population': 'Geriatric', 'Device_Class': 'Class I', 'Device_Weight_kg': 37.87, 'Device_Lifetime_Years': 11.0, 'combined_text': 'Device Name: Anesthesia Machine. Model: C-1766. Manufacturer: Edwards Lifesciences. Indications: Used for intraoperative sterilization monitoring during complex oncological surgeries.. Contraindications: Avoid use in patients with active hepatic dysfunction or compromised respiratory function.', 'Number_of_Cautions': 30, 'Publication_Date': '2017-05-06', 'Model_Number': 'C-1766', 'Max_Operating_Temperature_C': 34.0, 'Manufacturer': 'Edwards Lifesciences'}]], 'distances': [[0.9251278638839722, 0.9255565404891968, 0.9680476188659668]]}